case = {
    'key': 'copd',
    'title': 'Caso de EPOC',
    'icon': 'lungs',
    'description': 'Paciente actualemte en oxigenoterapia que busca seguimiento médico.',
    'age': 65,
    'weight_in_kg': 70.0,
    'physical_requirements': 'Requiere oxígeno por cánula nasal, debe ingresar con concentrador/tanque de oxígeno',
    'socioeconomic_status': 'Clase media, Bogotá, Colombia',
    'female_name': 'Gustava Alberta Trujillo',
    'male_name': 'Gustavo Alberto Trujillo',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profesión: Antropólogo(a), ex profesor(a) de la Universidad Nacional, actualmente pensionado(a). Familia: Vive con dos gatos. Estado civil: Soltero(a), abierto a relaciones. Religión: Católico. Estilo de vida: Ex fumador empedernido, bebedor social, disfruta la filosofía de vida de vivir plenamente.',
    'chief_complaint': 'Seguimiento después de exacerbación de EPOC que requirió hospitalización hace un mes',
    'present_illness': 'Exacerbación reciente de EPOC hace un mes que requirió hospitalización. Actualmente en terapia de oxígeno a 2 L/min. Síntomas actuales: fatiga con esfuerzo mínimo, disnea después de caminar una cuadra, tos ocasional sin esputo, pérdida de peso sin intentarlo. El paciente quiere una discusión honesta sobre su condición y pronóstico.',
    'personal_medical_history': 'EPOC diagnosticado hace 5 años después de un episodio severo de disnea. Infarto de miocardio hace 5 años, se colocó stent en arteria coronaria (arteria coronaria derecha).',
    'surgical_history': 'Resección de leucoplaquia oral hace varios años',
    'family_history': 'El padre también tuvo EPOC, era fumador más empedernido que el paciente',
    'medications': 'ASA de 100mg diario, bromuro de ipratropio de 2 inhalaciones dos veces al día, salbutamol según necesidad para exacerbaciones',
    'habits': 'Ex fumador(a) empedernido (24 cigarrillos/día por 50 años), dejó de fumar hace 5 años. Consumo social de alcohol (3 whiskies los fines de semana). Comenzó ejercicio en bicicleta estática pero experimenta disnea. Dieta: Trata de evitar gaseosas y productos de harina pero admite disfrutar la buena comida.',
    'allergies': 'Ninguna conocida',
    'concerns': 'Quiere mantener calidad de vida a pesar de la enfermedad avanzada. Preocupado por la frecuencia de ataques de disnea que afectan las actividades diarias. Preguntas sobre pronóstico y posibilidad de volver a la vida normal.',
}
