case = {
    'key': 'copd',
    'title': 'COPD Case',
    'icon': 'lungs',
    'description': 'Patient currently on oxygen therapy and seeking follow-up care.',
    'age': 65,
    'weight_in_kg': 70.0,
    'physical_requirements': 'Requires oxygen by nasal cannula, must enter with oxygen concentrator/tank',
    'socioeconomic_status': 'Middle class, Bogotá, Colombia',
    'female_name': 'Laura Trujillo',
    'male_name': 'Gustavo Alberto Trujillo',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profession: Anthropologist, former professor at National University, currently retired. Family: Lives with two cats. Marital status: Single, open to relationships. Religion: Catholic. Lifestyle: Former heavy smoker, social drinker, enjoys life philosophy of living fully.',
    'chief_complaint': 'Follow-up after COPD exacerbation requiring hospitalization one month ago',
    'present_illness': 'Recent COPD exacerbation one month ago requiring hospitalization. Currently on oxygen therapy at 2 L/min. Current symptoms: fatigue with minimal exertion, dyspnea after walking one block, occasional cough without sputum, weight loss without trying. Patient wants honest discussion about condition and prognosis.',
    'personal_medical_history': 'COPD diagnosed 5 years ago after severe dyspnea episode. Myocardial infarction 5 years ago, had coronary artery stent placement (right coronary artery).',
    'surgical_history': 'Oral leukoplakia resection several years ago',
    'family_history': 'Father also had COPD, was heavier smoker than patient',
    'medications': 'ASA 100mg daily, ipratropium bromide 2 inhalations twice daily, salbutamol as needed for exacerbations',
    'habits': 'Former heavy smoker (24 cigarettes/day for 50 years), quit 5 years ago. Social alcohol consumption (3 whiskeys on weekends). Started stationary bike exercise but experiences dyspnea. Diet: Tries to avoid soda and flour products but admits to enjoying good food.',
    'allergies': 'None known',
    'concerns': 'Wants to maintain quality of life despite advanced disease. Concerned about frequency of dyspnea attacks affecting daily activities. Questions about prognosis and possibility of returning to normal life.',
}
