case = {
    'key': 'diabetes',
    'title': 'Diabetes Mellitus',
    'icon': 'diabetes',
    'description': 'Patient with diabetes seeking medical follow-up.',
    'age': 70,
    'weight_in_kg': 85.0,
    'physical_requirements': 'Very disciplined patient with medications and with the management of the condition',
    'socioeconomic_status': 'High stratum, retired',
    'female_name': 'María Antonia Guzmán',
    'male_name': 'Mario Antonio Guzmán',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profession or occupation: Has been retired for 12 years. Family: Has a spouse, two children and a granddaughter named Gabriela. Marital status: Married. Class: High. Religion: Catholic',
    'chief_complaint': 'Quarterly control of type 2 diabetes mellitus',
    'present_illness': 'Type 2 diabetes with 13 years of evolution and 11 years of management at Fundación Santa fe de Bogotá. Reports feeling well, no visual symptoms, does not complain of polyuria polydipsia, reports non-significant weight loss, there is a feeling of well-being',
    'personal_medical_history': 'Type 2 diabetes mellitus with 13 years of evolution, 11 years of management at Fundación Santa fe de Bogotá. Myocardial infarction 9 years ago, cholecystectomy 2 years ago for acute cholecystitis, two lipomas, hypothyroidism',
    'surgical_history': 'Cholecystectomy 2 years ago for acute cholecystitis, transurethral prostatectomy',
    'family_history': 'Father died from heart attack, mother was diabetic, siblings have blood sugar problems',
    'medications': 'Rosuvastatin 20mg, sitagliptin 50mg, metoprolol 25mg twice daily, ASA 100mg, levothyroxine 50mg, enalapril 5mg once daily',
    'habits': 'Very disciplined with medications and lifestyle. Exercise: 35 minutes daily, 6 days per week with 1 rest day. Diet: Breakfast - coffee with milk sweetened with stevia, papaya and melon; Lunch - consommé, protein (meat/chicken/fish), salad, one serving of carbohydrates; Snack - oatmeal and/or fruit; Dinner - coffee with arepa paisa. No juices or regular soda, drinks Coca Cola Zero. Occasional alcohol at family gatherings, 2 beers when national team plays.',
    'allergies': 'None',
    'concerns': 'Wants to know overall health status, feels well but concerned about diabetes as silent killer. Sometimes struggles with dietary compliance, finds it challenging to avoid dietary temptations.',
} 