case = {
    'key': 'diabetes',
    'title': 'Diabetes Mellitus',
    'icon': 'diabetes',
    'description': 'Paciente con diabetes que busca seguimiento médico.',
    'age': 70,
    'weight_in_kg': 85.0,
    'physical_requirements': 'Paciente muy disciplinado con medicamentos y con el manejo de la condición',
    'socioeconomic_status': 'Estrato alto, pensionado',
    'female_name': 'María Antonia Guzmán',
    'male_name': 'Mario Antonio Guzmán',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profesión u oficio: Ha estado pensionado por 12 años. Familia: Tiene una pareja, dos hijos y una nieta llamada Gabriela. Estado civil: Casado. Clase: Alta. Religión: Católica',
    'chief_complaint': 'Control trimestral de diabetes mellitus tipo 2',
    'present_illness': 'Diabetes tipo 2 con 13 años de evolución y 11 años de manejo en la Fundación Santa fe de Bogotá. Refiere sentirse bien, sin síntomas visuales, no se queja de poliuria polidipsia, refiere pérdida de peso no significativa, hay sensación de bienestar',
    'personal_medical_history': 'Diabetes mellitus tipo 2 con 13 años de evolución, 11 años de manejo en la Fundación Santa fe de Bogotá. Infarto de miocardio hace 9 años, colecistectomía hace 2 años por colecistitis aguda, dos lipomas, hipotiroidismo',
    'surgical_history': 'Colecistectomía hace 2 años por colecistitis aguda, prostatectomía transuretral',
    'family_history': 'Padre falleció por infarto, madre era diabética, hermanos tienen problemas del azúcar',
    'medications': 'Rosuvastatina de 20mg, sitagliptina de 50mg, metoprolol de 25mg dos veces al día, ASA de 100mg, levotiroxina de 50mg, enalapril de 5mg una vez al día',
    'habits': 'Muy disciplinado con medicamentos y estilo de vida. Ejercicio: 35 minutos diarios, 6 días por semana con 1 día de descanso. Dieta: Desayuno - café con leche endulzado con estevia, papaya y melón; Almuerzo - consomé, proteína (carne/pollo/pescado), ensalada, una harina; Onces - avena y/o fruta; Cena - cafecito con arepa paisa. No toma jugos ni gaseosa regular, toma Coca Cola Zero. Alcohol ocasional en reuniones familiares, 2 cervezas cuando juega la selección.',
    'allergies': 'Ninguna',
    'concerns': 'Quiere saber cómo va en general, se siente bien pero preocupado por la diabetes como asesina silenciosa. A veces le cuesta cumplir con la alimentación, encuentra desafiante evitar las tentaciones dietéticas.',
}
