case = {
    'key': 'dyslipidemia',
    'title': 'Caso de Dislipidemia',
    'icon': 'heart',
    'description': 'Paciente remitido de medicina general para evaluación de riesgo cardiovascular debido a antecedentes familiares.',
    'age': 53,
    'weight_in_kg': 80.0,
    'physical_requirements': 'Ninguno',
    'socioeconomic_status': 'Clase alta, ingeniero(a) de sistemas, vive en Chía',
    'female_name': 'Sofia Martinez',
    'male_name': 'Carlos Martinez',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profesión: Ingeniero(a) de sistemas en Sony. Familia: Tiene pareja y 3 hijos, vive con dos de ellos, uno está en el extranjero en Canadá. Estado civil: Casado. Religión: Católico. Esquema completo de vacunación contra COVID.',
    'chief_complaint': 'Remitido de medicina general para evaluación de riesgo cardiovascular',
    'present_illness': 'Comenzó a notar dolor en pierna derecha especialmente durante caminatas matutinas. El dolor solo ocurre al caminar y se alivia con el reposo. El paciente entiende que esto puede indicar problemas arteriales y debido a antecedentes familiares de infarto, decidió hacerse chequeo. Recientemente se ha dado más lujos con comida chatarra como pizza, hamburguesas, papas fritas, y ha subido de peso.',
    'personal_medical_history': 'Dislipidemia conocida. Colecistectomía hace 15 años por cálculos biliares.',
    'surgical_history': 'Colecistectomía hace 15 años por cálculos biliares',
    'family_history': 'Varios integrantes de la familia han sufrido de enfermedad cardíaca y han tenido infartos, incluyendo al padre que falleció por infarto a los 51 años',
    'medications': 'ASA de 81mg diario (comenzó a tomar porque vio en propaganda que todos los mayores de 50 deben tomar diario para el corazón), atorvastatina de 40mg en la noche prescrita por médico general',
    'habits': 'Consumo social de alcohol los fines de semana con amigos mientras juegan póker. Fuma 2 cigarrillos diarios y ocasionalmente usa marihuana. Recientemente aumentó consumo de comida chatarra y ha subido de peso.',
    'allergies': 'Ninguna',
    'concerns': 'Consciente del alto riesgo familiar de infarto y quiere prevenirlo. Dispuesto a bajar de peso, reducir grasas y seguir recomendaciones médicas.',
}
