case = {
    'key': 'dyslipidemia',
    'title': 'Dyslipidemia Case',
    'icon': 'heart',
    'description': 'Patient referred from general medicine for cardiovascular risk assessment due to family history.',
    'age': 53,
    'weight_in_kg': 80.0,
    'physical_requirements': 'None',
    'socioeconomic_status': 'High class, systems engineer, lives in Chía',
    'female_name': 'Sofia Martinez',
    'male_name': 'Carlos Martinez',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profession: Systems engineer at Sony. Family: Has spouse and 3 children, lives with two of them, one is abroad in Canada. Marital status: Married. Religion: Catholic. Complete COVID vaccination scheme.',
    'chief_complaint': 'Referred from general medicine for cardiovascular risk assessment',
    'present_illness': 'Started noticing pain in right leg especially during morning walks. Pain only occurs when walking and subsides with rest. Patient understands this may indicate arterial problems and due to family history of heart attack, decided to get checked. Recently indulging in more junk food like pizza, hamburgers, fries, and has gained weight.',
    'personal_medical_history': 'Known dyslipidemia. Cholecystectomy 15 years ago for gallstones.',
    'surgical_history': 'Cholecystectomy 15 years ago for gallstones',
    'family_history': 'Several family members have suffered from heart disease and had heart attacks, including father who died from heart attack at age 51',
    'medications': 'ASA 81mg daily (started taking because of advertisement saying everyone over 50 should take daily for heart), atorvastatin 40mg at night prescribed by general physician',
    'habits': 'Weekend social drinking with friends while playing poker. Smokes 2 cigarettes daily and occasionally uses marijuana. Recently increased consumption of junk food and has gained weight.',
    'allergies': 'None',
    'concerns': 'Aware of high family risk of heart attack and wants to prevent it. Willing to lose weight, reduce fats, and follow medical recommendations.',
}
