case = {
    'key': 'hypothyroidism',
    'title': 'Hypothyroidism Case',
    'icon': 'thyroid',
    'description': 'Patient of 40 years with physical fatigue (asthenia) and multiple symptoms affecting daily activities.',
    'age': 40,
    'weight_in_kg': 70.0,
    'physical_requirements': 'None',
    'socioeconomic_status': 'High class, lives in Modelia, Bogota, Colombia',
    'female_name': 'Angelina Suárez',
    'male_name': 'Ángel Suárez',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profession: Systems engineer in technology company, MBA student. Family: Stable partner for 7 years, partner travels frequently (Avianca pilot), shares expenses. Marital status: Free union. Religion: Catholic. Complete vaccination scheme - 3 doses of Pfizer without booster',
    'chief_complaint': 'Very tired, does not want to do anything',
    'present_illness': 'For 1 year has felt without energy, more noticeable in last 2 months. Difficulty with daily work activities due to fatigue, decreased mental productivity. Fatigue affecting private life (decreased sexual life), cold intolerance. Skin and nails: Break frequently, very dry skin for 2 years. Hair: Hair loss for 2 years, more pronounced in last 8 months, widened entrances. Gastrointestinal: Epigastric pain, constipation for 1 year, sometimes up to 1 week between bowel movements. Mental/psychological: Sadness, unmotivated, sometimes no energy to get out of bed, lost interest in computers and video games. Weight changes: Clothes fitting tighter, possible weight gain. Cardiorespiratory: Recent fatigue with stairs, difficulty breathing, shortness of breath.',
    'personal_medical_history': 'Recent flu episodes, increased cold sensitivity.',
    'surgical_history': 'Cholelithiasis at 15 years old, laparoscopic without complications',
    'family_history': 'Mother suffers from controlled diabetes with two medications, a great-grandfather suffered from Alzheimer\'s and the rest are healthy',
    'medications': 'None, was quite healthy',
    'habits': 'Non-smoker, social alcohol consumption. Stopped exercising 7 months ago due to lack of motivation and time constraints. Diet: Prefers fish and chicken over red meat, drinks 3+ cups of coffee daily due to fatigue.',
    'allergies': 'None known',
    'concerns': 'Concerned about persistent fatigue, irritable and unmotivated mood, expresses anguish about life meaning. Questions: What is happening to me?',
}
