case = {
    'key': 'hypothyroidism',
    'title': 'Caso de Hipotiroidismo',
    'icon': 'thyroid',
    'description': 'Paciente de 40 años con fatiga física (astenia) y múltiples síntomas que afectan las actividades diarias.',
    'age': 40,
    'weight_in_kg': 70.0,
    'physical_requirements': 'Ninguno',
    'socioeconomic_status': 'Clase alta, vive en Modelia, Bogotá, Colombia',
    'female_name': 'Angelina Suárez',
    'male_name': 'Ángel Suárez',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profesión: Ingeniero(a) de sistemas en empresa de tecnología, estudiante de MBA. Familia: Pareja estable por 7 años, la pareja viaja frecuentemente (piloto de Avianca), comparten gastos. Estado civil: Unión libre. Religión: Católica. Esquema completo de vacunación - 3 dosis de Pfizer sin refuerzo',
    'chief_complaint': 'Muy cansado, no quiere hacer nada',
    'present_illness': 'Por 1 año se ha sentido sin energía, más notable en los últimos 2 meses. Dificultad con actividades laborales diarias debido a fatiga, disminución de productividad mental. Fatiga afectando la vida privada (disminución de vida sexual), intolerancia al frío. Piel y uñas: Se rompen frecuentemente, piel muy seca por 2 años. Cabello: Pérdida de cabello por 2 años, más pronunciada en los últimos 8 meses, entradas ampliadas. Gastrointestinal: Dolor epigástrico, estreñimiento por 1 año, a veces hasta 1 semana entre deposiciones. Mental/psicológico: Tristeza, desmotivado, a veces sin energía para levantarse de la cama, perdió interés en computadores y videojuegos. Cambios de peso: Ropa ajustándose más, posible aumento de peso. Cardiorrespiratorio: Fatiga reciente con escaleras, dificultad para respirar, falta de aire.',
    'personal_medical_history': 'Episodios recientes de gripa, mayor sensibilidad al frío.',
    'surgical_history': 'Colelitiasis a los 15 años, laparoscópica sin complicaciones',
    'family_history': 'La madre sufre de diabetes controlada con dos medicamentos, un bisabuelo sufrió de Alzheimer y el resto están sanos',
    'medications': 'Ninguna, era bastante sano',
    'habits': 'No fumador(a), consumo social de alcohol. Dejó de hacer ejercicio hace 7 meses debido a falta de motivación y limitaciones de tiempo. Dieta: Prefiere pescado y pollo sobre carne roja, bebe 3+ tazas de café diarias debido a fatiga.',
    'allergies': 'Ninguna conocida',
    'concerns': 'Preocupado por fatiga persistente, estado de ánimo irritable y desmotivado, expresa angustia sobre el significado de la vida. Preguntas: ¿Qué me está pasando?',
}
