case = {
    'key': 'joint_pain',
    'title': 'Caso de Dolor Articular',
    'icon': 'bone',
    'description': 'Paciente de 45 años con historia de 8 semanas de dolor en manos y muñecas.',
    'age': 45,
    'weight_in_kg': 70.0,
    'gender_restriction': 'female',
    'physical_requirements': 'Presenta reocupación, dolor suave pero constante en manos, manos con leve eritema en nudillos (tono rosa suave)',
    'socioeconomic_status': 'Estrato medio, Bogotá, Colombia',
    'female_name': 'Josefina Manuela Rincon',
    'male_name': 'José Manuel Rincon',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profesión: Oficinista, trabaja en firma de abogados desde hace 12 años. Familia: Tiene 1 hijo de 13 años, divorciado. Actualmente mantiene relación con alguien de la empresa. Estado civil: Viudez a los 40 años. Religión: No tiene religión. Esquema completo de vacunación contra COVID - Janssen desde hace un año, sin más refuerzos.',
    'chief_complaint': 'Rigidez y dolor en manos, afectando rendimiento laboral y requiriendo descansos frecuentes',
    'present_illness': 'Historia de 8 semanas de dolor en manos y muñecas, peor en horas de la madrugada y al despertar, mejora después de aproximadamente 1 hora de actividades diarias. Por varios meses notó leve malestar en hombros y pies (rigidez con dolor al movimiento) pero le restó importancia ya que no impedía actividades diarias. En la última semana notó aparición de manchas rojas en dorso de manos (especialmente en nudillos) lo que le asustó, también notó que las manos se ponen hinchadas, rígidas y con dolor soportable pero incómodo. Todo esto no le está dificultando realizar actividades diarias ni tareas domésticas. Siente que ha estado más cansado y con menos energía para actividades que antes realizaba sin limitación. En los últimos días no ha podido abrir y cerrar las manos como antes, incluso nota que los dedos se le desvían.',
    'personal_medical_history': 'Ninguna, se considera persona sana y activa. Mujer: 1 embarazo, parto sin complicaciones a los 32 años. Primera regla a los 12 años, menstruación regular cada 28 días. Vida sexual activa desde hace 2 años después de enviudar.',
    'surgical_history': 'En la niñez se sacaron las amígdalas y también al año de eso se sacó el apéndice, entre los 12 y 13 años',
    'family_history': 'La nana de la niñez, que quería mucho, tenía las manos un poco torcidas cuando le cuidaba, casi no le podía alzar, eso siempre le llamó la atención',
    'medications': 'Ibuprofeno de 200 a 400mg vía oral cuando tiene mucho dolor, algo alivia el dolor pero no lo usa casi porque le da molestias gástricas. Si es Mujer: usa anticonceptivos orales desde que inició nuevamente vida sexual hace 2 años.',
    'habits': 'No hace ejercicio porque no le queda tiempo, a veces toma cervezas en asados el fin de semana, no fuma ni consume drogas, come lo que haya. A veces se excede con las harinas, toma poca agua, consume mucho café y sodas.',
    'allergies': 'Ninguna que recuerde, tal vez en la niñez algunas flores le daban estornudos',
    'concerns': '¿Me voy a curar? ¿Este dolor me va a durar toda la vida? ¿Cómo voy a hacer para trabajar? ¿Voy a estar en una silla de ruedas? ¿Qué va a pasar con mi hijo si yo no puedo estar ahí cuando me necesite?',
}
