case = {
    'key': 'joint_pain',
    'title': 'Joint Pain Case',
    'icon': 'bone',
    'description': 'Patient of 45 years with 8-week history of pain in hands and wrists',
    'age': 45,
    'weight_in_kg': 70.0,
    'physical_requirements': 'Concerned expression, mild but constant pain in hands, mild erythema on knuckles (soft pink tone)',
    'socioeconomic_status': 'Middle class, Bogotá, Colombia',
    'gender_restriction': 'female',
    'female_name': 'Josefina Manuela Rincon',
    'male_name': 'José Manuel Rincon',
    'female_photo': '',
    'male_photo': '',
    'patient_context': 'Profession: Office worker, works at law firm for 12 years. Family: Has 1 child age 13, divorced. Currently in relationship with company colleague. Marital status: Widowed at age 40. Religion: No religion. Complete COVID vaccination scheme - Janssen one year ago, no boosters.',
    'chief_complaint': 'Stiffness and pain in hands, affecting work performance and requiring frequent breaks',
    'present_illness': '8-week history of pain in hands and wrists, worse in early morning hours and upon waking, improves after approximately 1 hour of daily activities. For several months noticed mild discomfort in shoulders and feet (stiffness with pain on movement) but ignored it as it did not prevent daily activities. In last week noticed red spots on back of hands (especially on knuckles) which frightened patient, also noticed hands become swollen, stiff and with bearable but uncomfortable pain. All of this is not preventing daily activities or household chores. Feels more tired and with less energy for activities previously done without limitation. In recent days cannot open and close hands as before, even notices fingers seem to deviate.',
    'personal_medical_history': 'None, considers self healthy and active. Woman: 1 pregnancy, uncomplicated delivery at age 32. First menstruation at age 12, regular 28-day cycles. Active sexual life for 2 years after becoming widowed.',
    'surgical_history': 'Tonsillectomy in childhood, appendectomy between ages 12-13',
    'family_history': 'Childhood nanny had hands that were somewhat twisted, could barely lift patient when caring for them, this always caught attention',
    'medications': 'Ibuprofen 200-400mg orally when having severe pain, provides some relief but rarely used due to gastric discomfort. If Woman: Uses oral contraceptives for 2 years since resuming sexual activity.',
    'habits': 'No exercise due to lack of time, occasional beers at weekend barbecues, does not smoke or use drugs. Eats whatever is available, sometimes exceeds with flour products, drinks little water, consumes much coffee and sodas.',
    'allergies': 'None remembered, perhaps some flowers caused sneezing in childhood',
    'concerns': 'Will I be cured? Will this pain last my whole life? How will I work? Will I end up in a wheelchair? What will happen to my child if I cannot be there when needed?',
}
