"""Provider-independent speech request and response contracts."""

from dataclasses import dataclass
from enum import Enum
from typing import Protocol


class SpeechError(RuntimeError):
    """Base exception for speech operations."""


class SpeechConfigurationError(SpeechError):
    """Raised when a selected speech provider is not configured."""


class SpeechProviderError(SpeechError):
    """Raised when a configured provider rejects a speech request."""


class SpeakingRate(str, Enum):
    """Provider-neutral speaking-rate categories."""

    MODERATELY_SLOW = "moderately_slow"
    MODERATE = "moderate"
    BRISK = "brisk"


class PauseFrequency(str, Enum):
    """Provider-neutral frequency of natural speech pauses."""

    SPARSE = "sparse"
    NATURAL = "natural"
    OCCASIONAL = "occasional"
    FREQUENT = "frequent"


class VocalEnergy(str, Enum):
    """Provider-neutral vocal-energy categories."""

    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class IntonationVariation(str, Enum):
    """Provider-neutral intonation-variation categories."""

    RESTRAINED = "restrained"
    NATURAL = "natural"
    EXPRESSIVE = "expressive"


class HesitationFrequency(str, Enum):
    """Provider-neutral vocal-hesitation categories."""

    NONE = "none"
    LIGHT = "light"
    OCCASIONAL = "occasional"


class DeliveryTone(str, Enum):
    """Configured acting direction, not an inferred psychological state."""

    NEUTRAL = "neutral"
    REASSURING = "reassuring"
    SELF_ASSURED = "self_assured"
    IMPATIENT = "impatient"
    UNCERTAIN = "uncertain"
    REFLECTIVE = "reflective"


@dataclass(frozen=True)
class VocalStyle:
    """Structured paraverbal directions independent from any TTS provider."""

    profile_key: str
    policy_version: str
    speaking_rate: SpeakingRate
    pause_frequency: PauseFrequency
    energy: VocalEnergy
    intonation_variation: IntonationVariation
    hesitation_frequency: HesitationFrequency
    delivery_tone: DeliveryTone


@dataclass(frozen=True)
class SpeechSynthesisRequest:
    """Neutral text-to-speech request."""

    text: str
    voice: str
    response_format: str = "mp3"
    vocal_style: VocalStyle | None = None


@dataclass(frozen=True)
class SynthesizedAudio:
    """Audio generated by a text-to-speech provider."""

    content: bytes
    content_type: str
    provider: str
    model: str
    voice: str | None = None
    style_policy_version: str | None = None
    synthesis_instructions: str | None = None


@dataclass(frozen=True)
class SpeechTranscriptionRequest:
    """Neutral speech-to-text request."""

    content: bytes
    filename: str
    content_type: str
    language: str | None = None


@dataclass(frozen=True)
class TranscriptionResult:
    """Text returned by a speech-to-text provider."""

    text: str
    language: str | None
    provider: str
    model: str


class TextToSpeechProvider(Protocol):
    """Contract implemented by text-to-speech providers."""

    def synthesize(self, request: SpeechSynthesisRequest) -> SynthesizedAudio:
        """Generate audio for one request."""


class SpeechToTextProvider(Protocol):
    """Contract implemented by speech-to-text providers."""

    def transcribe(self, request: SpeechTranscriptionRequest) -> TranscriptionResult:
        """Transcribe one audio payload."""
